services:
  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    environment:
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
    ports:
      - "8200:8200"
    volumes:
      - /srv/duplicati/data:/data
      - /srv:/source/srv:ro
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
