services:
  vaultwarden:
    image: vaultwarden/server:1.37.3
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${VW_DOMAIN}
      SIGNUPS_ALLOWED: ${VW_SIGNUPS_ALLOWED}
    volumes:
      - /srv/vaultwarden/vw-data:/data/
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
