services:
  kopia:
    image: kopia/kopia:20260927.0.53511
    container_name: kopia
    hostname: kopia
    restart: unless-stopped
    ports:
      - "51515:51515"
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_WEBUI_USER}
      - --server-password=${KOPIA_WEBUI_PASSWORD}
    environment:
      KOPIA_PASSWORD: "${KOPIA_MASTER_PASSWORD}"
      USER: "${KOPIA_SYSTEM_USER}"
    volumes:
      - /srv/kopia/config:/app/config
      - /srv/kopia/cache:/app/cache
      - /srv/kopia/logs:/app/logs
      - /srv:/data:ro
      - /srv/kopia/gdrive-key.json:/app/gdrive-key.json:ro

    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
